name: Deploy to Ubuntu

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

            - name: Deploy with rsync
              run: |
                  rsync -avz --delete \
                    --exclude-from='.deployignore' \
                    ./ \
                    ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PATH }}

            - name: Install dependencies & restart app
              run: |
                  ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
                    pwd
                    cd /home/xers/xers-info
                    pm2 kill
                    nvm use 24
                    npm install --production
                    NODE_ENV=production node sync-database.js
                    NODE_ENV=production pm2 start app.js
                    NODE_ENV=production pm2 restart app.js --update-env
                  EOF
