name: Deploy to Ubuntu

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js 24
              uses: actions/setup-node@v3
              with:
                  node-version: 24
                  cache: "npm"

            - name: Check Node and npm versions
              run: |
                  node -v
                  npm -v

            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
                  chmod 600 ~/.ssh/id_ed25519
                  ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

            - name: Deploy with rsync
              run: |
                  rsync -avz --delete \
                    --exclude-from='.deployignore' \
                    ./ \
                    ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PATH }}

            - name: Install dependencies & restart app
              run: |
                  ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
                    pwd
                    cd /home/xers/xers-info
                    echo "nvm use 24 **********************************"
                    nvm use 24
                    echo "pm2 kill **********************************"
                    pm2 kill
                    echo "npm install --production **********************************"
                    npm install --production
                    echo "node sync-database.js ***********************************"
                    NODE_ENV=production node sync-database.js
                    NODE_ENV=production pm2 start app.js
                    NODE_ENV=production pm2 restart app.js --update-env
                  EOF
